global:
  chartName: orders
  deployment:
    imageTag: 0.1.1
orders:
  # Deployment object
  deployment:
    enabled: true
    name: orders
    namespace: ecommerce
    replicas: 1
    appName: orders
    role: api
    containerName: orders-container
    imageRepository: 798842239772.dkr.ecr.us-east-1.amazonaws.com/ecommerce-orders
    imageTag: 0.1.1
    port: 3003
  # Updated (New) Deployment resource
  newDeployment:
    enabled: false
  # Horizontal Pod Autoscaler
  hpa:
    enabled: false
  # Service Account object
  serviceAccount:
    enabled: true
    name: orders-service-account
    namespace: ecommerce
  # Stable Service object
  service:
    enabled: true
    name: orders-service
    namespace: ecommerce
    appName: orders
    type: ClusterIP
    servicePort: 3003
    targetPort: 3003
  # Canary Service object (for Argo Rollouts)
  canaryService:
    enabled: false
  # Namespace object
  namespace:
    enabled: false
  # Ingress 
  ingress:
    enabled: false
  # Canary Rollout # Canary Service object (for Argo Rollouts)
  canaryRollout:
    enabled: false
  # Istio - Gateway 
  gateway:
    enabled: false
  # Istio - VirtualService 
  virtualservice:
    enabled: false
