{{- if .Values.virtualservice.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name }}
  namespace: {{ .Values.virtualservice.namespace }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.gateway.name }}
  http:
  - route:
    - destination:
        host: {{ .Values.service.name }}.{{ .Values.service.namespace }}.svc.cluster.local
        port:
          number: {{ .Values.service.servicePort }}
{{- end }}
